// Code generated by mockery v2.44.1. DO NOT EDIT.

package resourceapi

import (
	context "context"

	resourceapi "github.com/arisu-archive/assets-dumper/pkg/resourceapi"
	mock "github.com/stretchr/testify/mock"
)

// MockRetriever is an autogenerated mock type for the Retriever type
type MockRetriever struct {
	mock.Mock
}

type MockRetriever_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRetriever) EXPECT() *MockRetriever_Expecter {
	return &MockRetriever_Expecter{mock: &_m.Mock}
}

// CollectAllResources provides a mock function with given fields: ctx
func (_m *MockRetriever) CollectAllResources(ctx context.Context) ([]resourceapi.Resource, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CollectAllResources")
	}

	var r0 []resourceapi.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]resourceapi.Resource, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []resourceapi.Resource); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resourceapi.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRetriever_CollectAllResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectAllResources'
type MockRetriever_CollectAllResources_Call struct {
	*mock.Call
}

// CollectAllResources is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRetriever_Expecter) CollectAllResources(ctx interface{}) *MockRetriever_CollectAllResources_Call {
	return &MockRetriever_CollectAllResources_Call{Call: _e.mock.On("CollectAllResources", ctx)}
}

func (_c *MockRetriever_CollectAllResources_Call) Run(run func(ctx context.Context)) *MockRetriever_CollectAllResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRetriever_CollectAllResources_Call) Return(_a0 []resourceapi.Resource, _a1 error) *MockRetriever_CollectAllResources_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRetriever_CollectAllResources_Call) RunAndReturn(run func(context.Context) ([]resourceapi.Resource, error)) *MockRetriever_CollectAllResources_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRetriever creates a new instance of MockRetriever. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRetriever(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRetriever {
	mock := &MockRetriever{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
