// Code generated by mockery v2.53.3. DO NOT EDIT.

package resourceapi

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	resourceapi "github.com/arisu-archive/assets-dumper/pkg/resourceapi"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DownloadApplication provides a mock function with given fields: ctx
func (_m *MockClient) DownloadApplication(ctx context.Context) (io.ReadCloser, int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DownloadApplication")
	}

	var r0 io.ReadCloser
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (io.ReadCloser, int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) io.ReadCloser); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) int64); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockClient_DownloadApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadApplication'
type MockClient_DownloadApplication_Call struct {
	*mock.Call
}

// DownloadApplication is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) DownloadApplication(ctx interface{}) *MockClient_DownloadApplication_Call {
	return &MockClient_DownloadApplication_Call{Call: _e.mock.On("DownloadApplication", ctx)}
}

func (_c *MockClient_DownloadApplication_Call) Run(run func(ctx context.Context)) *MockClient_DownloadApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_DownloadApplication_Call) Return(_a0 io.ReadCloser, _a1 int64, _a2 error) *MockClient_DownloadApplication_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockClient_DownloadApplication_Call) RunAndReturn(run func(context.Context) (io.ReadCloser, int64, error)) *MockClient_DownloadApplication_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadPatch provides a mock function with given fields: ctx, patchPath
func (_m *MockClient) DownloadPatch(ctx context.Context, patchPath string) (io.ReadCloser, int64, error) {
	ret := _m.Called(ctx, patchPath)

	if len(ret) == 0 {
		panic("no return value specified for DownloadPatch")
	}

	var r0 io.ReadCloser
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, int64, error)); ok {
		return rf(ctx, patchPath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, patchPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int64); ok {
		r1 = rf(ctx, patchPath)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, patchPath)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockClient_DownloadPatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadPatch'
type MockClient_DownloadPatch_Call struct {
	*mock.Call
}

// DownloadPatch is a helper method to define mock.On call
//   - ctx context.Context
//   - patchPath string
func (_e *MockClient_Expecter) DownloadPatch(ctx interface{}, patchPath interface{}) *MockClient_DownloadPatch_Call {
	return &MockClient_DownloadPatch_Call{Call: _e.mock.On("DownloadPatch", ctx, patchPath)}
}

func (_c *MockClient_DownloadPatch_Call) Run(run func(ctx context.Context, patchPath string)) *MockClient_DownloadPatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_DownloadPatch_Call) Return(_a0 io.ReadCloser, _a1 int64, _a2 error) *MockClient_DownloadPatch_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockClient_DownloadPatch_Call) RunAndReturn(run func(context.Context, string) (io.ReadCloser, int64, error)) *MockClient_DownloadPatch_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadResource provides a mock function with given fields: ctx, resourcePath
func (_m *MockClient) DownloadResource(ctx context.Context, resourcePath string) (io.ReadCloser, int64, error) {
	ret := _m.Called(ctx, resourcePath)

	if len(ret) == 0 {
		panic("no return value specified for DownloadResource")
	}

	var r0 io.ReadCloser
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, int64, error)); ok {
		return rf(ctx, resourcePath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, resourcePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int64); ok {
		r1 = rf(ctx, resourcePath)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, resourcePath)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockClient_DownloadResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadResource'
type MockClient_DownloadResource_Call struct {
	*mock.Call
}

// DownloadResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resourcePath string
func (_e *MockClient_Expecter) DownloadResource(ctx interface{}, resourcePath interface{}) *MockClient_DownloadResource_Call {
	return &MockClient_DownloadResource_Call{Call: _e.mock.On("DownloadResource", ctx, resourcePath)}
}

func (_c *MockClient_DownloadResource_Call) Run(run func(ctx context.Context, resourcePath string)) *MockClient_DownloadResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_DownloadResource_Call) Return(_a0 io.ReadCloser, _a1 int64, _a2 error) *MockClient_DownloadResource_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockClient_DownloadResource_Call) RunAndReturn(run func(context.Context, string) (io.ReadCloser, int64, error)) *MockClient_DownloadResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetCatalog provides a mock function with given fields: ctx, catalogType
func (_m *MockClient) GetCatalog(ctx context.Context, catalogType resourceapi.CatalogType) (interface{}, error) {
	ret := _m.Called(ctx, catalogType)

	if len(ret) == 0 {
		panic("no return value specified for GetCatalog")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, resourceapi.CatalogType) (interface{}, error)); ok {
		return rf(ctx, catalogType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, resourceapi.CatalogType) interface{}); ok {
		r0 = rf(ctx, catalogType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, resourceapi.CatalogType) error); ok {
		r1 = rf(ctx, catalogType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCatalog'
type MockClient_GetCatalog_Call struct {
	*mock.Call
}

// GetCatalog is a helper method to define mock.On call
//   - ctx context.Context
//   - catalogType resourceapi.CatalogType
func (_e *MockClient_Expecter) GetCatalog(ctx interface{}, catalogType interface{}) *MockClient_GetCatalog_Call {
	return &MockClient_GetCatalog_Call{Call: _e.mock.On("GetCatalog", ctx, catalogType)}
}

func (_c *MockClient_GetCatalog_Call) Run(run func(ctx context.Context, catalogType resourceapi.CatalogType)) *MockClient_GetCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(resourceapi.CatalogType))
	})
	return _c
}

func (_c *MockClient_GetCatalog_Call) Return(_a0 interface{}, _a1 error) *MockClient_GetCatalog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetCatalog_Call) RunAndReturn(run func(context.Context, resourceapi.CatalogType) (interface{}, error)) *MockClient_GetCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestPatchVersion provides a mock function with given fields: ctx
func (_m *MockClient) GetLatestPatchVersion(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestPatchVersion")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetLatestPatchVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestPatchVersion'
type MockClient_GetLatestPatchVersion_Call struct {
	*mock.Call
}

// GetLatestPatchVersion is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) GetLatestPatchVersion(ctx interface{}) *MockClient_GetLatestPatchVersion_Call {
	return &MockClient_GetLatestPatchVersion_Call{Call: _e.mock.On("GetLatestPatchVersion", ctx)}
}

func (_c *MockClient_GetLatestPatchVersion_Call) Run(run func(ctx context.Context)) *MockClient_GetLatestPatchVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_GetLatestPatchVersion_Call) Return(_a0 string, _a1 error) *MockClient_GetLatestPatchVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetLatestPatchVersion_Call) RunAndReturn(run func(context.Context) (string, error)) *MockClient_GetLatestPatchVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestVersion provides a mock function with given fields: ctx
func (_m *MockClient) GetLatestVersion(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestVersion")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetLatestVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestVersion'
type MockClient_GetLatestVersion_Call struct {
	*mock.Call
}

// GetLatestVersion is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) GetLatestVersion(ctx interface{}) *MockClient_GetLatestVersion_Call {
	return &MockClient_GetLatestVersion_Call{Call: _e.mock.On("GetLatestVersion", ctx)}
}

func (_c *MockClient_GetLatestVersion_Call) Run(run func(ctx context.Context)) *MockClient_GetLatestVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_GetLatestVersion_Call) Return(_a0 string, _a1 error) *MockClient_GetLatestVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetLatestVersion_Call) RunAndReturn(run func(context.Context) (string, error)) *MockClient_GetLatestVersion_Call {
	_c.Call.Return(run)
	return _c
}

// IsResourceCached provides a mock function with given fields: ctx, resource, fullPath
func (_m *MockClient) IsResourceCached(ctx context.Context, resource resourceapi.Resource, fullPath string) bool {
	ret := _m.Called(ctx, resource, fullPath)

	if len(ret) == 0 {
		panic("no return value specified for IsResourceCached")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, resourceapi.Resource, string) bool); ok {
		r0 = rf(ctx, resource, fullPath)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockClient_IsResourceCached_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsResourceCached'
type MockClient_IsResourceCached_Call struct {
	*mock.Call
}

// IsResourceCached is a helper method to define mock.On call
//   - ctx context.Context
//   - resource resourceapi.Resource
//   - fullPath string
func (_e *MockClient_Expecter) IsResourceCached(ctx interface{}, resource interface{}, fullPath interface{}) *MockClient_IsResourceCached_Call {
	return &MockClient_IsResourceCached_Call{Call: _e.mock.On("IsResourceCached", ctx, resource, fullPath)}
}

func (_c *MockClient_IsResourceCached_Call) Run(run func(ctx context.Context, resource resourceapi.Resource, fullPath string)) *MockClient_IsResourceCached_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(resourceapi.Resource), args[2].(string))
	})
	return _c
}

func (_c *MockClient_IsResourceCached_Call) Return(_a0 bool) *MockClient_IsResourceCached_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_IsResourceCached_Call) RunAndReturn(run func(context.Context, resourceapi.Resource, string) bool) *MockClient_IsResourceCached_Call {
	_c.Call.Return(run)
	return _c
}

// ListPatches provides a mock function with given fields: ctx, filter
func (_m *MockClient) ListPatches(ctx context.Context, filter string) ([]resourceapi.Resource, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListPatches")
	}

	var r0 []resourceapi.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]resourceapi.Resource, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []resourceapi.Resource); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resourceapi.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListPatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPatches'
type MockClient_ListPatches_Call struct {
	*mock.Call
}

// ListPatches is a helper method to define mock.On call
//   - ctx context.Context
//   - filter string
func (_e *MockClient_Expecter) ListPatches(ctx interface{}, filter interface{}) *MockClient_ListPatches_Call {
	return &MockClient_ListPatches_Call{Call: _e.mock.On("ListPatches", ctx, filter)}
}

func (_c *MockClient_ListPatches_Call) Run(run func(ctx context.Context, filter string)) *MockClient_ListPatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_ListPatches_Call) Return(_a0 []resourceapi.Resource, _a1 error) *MockClient_ListPatches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListPatches_Call) RunAndReturn(run func(context.Context, string) ([]resourceapi.Resource, error)) *MockClient_ListPatches_Call {
	_c.Call.Return(run)
	return _c
}

// ListResources provides a mock function with given fields: ctx, filter
func (_m *MockClient) ListResources(ctx context.Context, filter string) ([]resourceapi.Resource, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListResources")
	}

	var r0 []resourceapi.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]resourceapi.Resource, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []resourceapi.Resource); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resourceapi.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListResources'
type MockClient_ListResources_Call struct {
	*mock.Call
}

// ListResources is a helper method to define mock.On call
//   - ctx context.Context
//   - filter string
func (_e *MockClient_Expecter) ListResources(ctx interface{}, filter interface{}) *MockClient_ListResources_Call {
	return &MockClient_ListResources_Call{Call: _e.mock.On("ListResources", ctx, filter)}
}

func (_c *MockClient_ListResources_Call) Run(run func(ctx context.Context, filter string)) *MockClient_ListResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_ListResources_Call) Return(_a0 []resourceapi.Resource, _a1 error) *MockClient_ListResources_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListResources_Call) RunAndReturn(run func(context.Context, string) ([]resourceapi.Resource, error)) *MockClient_ListResources_Call {
	_c.Call.Return(run)
	return _c
}

// WithPatchVersion provides a mock function with given fields: patchVersion
func (_m *MockClient) WithPatchVersion(patchVersion string) resourceapi.Client {
	ret := _m.Called(patchVersion)

	if len(ret) == 0 {
		panic("no return value specified for WithPatchVersion")
	}

	var r0 resourceapi.Client
	if rf, ok := ret.Get(0).(func(string) resourceapi.Client); ok {
		r0 = rf(patchVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resourceapi.Client)
		}
	}

	return r0
}

// MockClient_WithPatchVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithPatchVersion'
type MockClient_WithPatchVersion_Call struct {
	*mock.Call
}

// WithPatchVersion is a helper method to define mock.On call
//   - patchVersion string
func (_e *MockClient_Expecter) WithPatchVersion(patchVersion interface{}) *MockClient_WithPatchVersion_Call {
	return &MockClient_WithPatchVersion_Call{Call: _e.mock.On("WithPatchVersion", patchVersion)}
}

func (_c *MockClient_WithPatchVersion_Call) Run(run func(patchVersion string)) *MockClient_WithPatchVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_WithPatchVersion_Call) Return(_a0 resourceapi.Client) *MockClient_WithPatchVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_WithPatchVersion_Call) RunAndReturn(run func(string) resourceapi.Client) *MockClient_WithPatchVersion_Call {
	_c.Call.Return(run)
	return _c
}

// WithVersion provides a mock function with given fields: version
func (_m *MockClient) WithVersion(version string) resourceapi.Client {
	ret := _m.Called(version)

	if len(ret) == 0 {
		panic("no return value specified for WithVersion")
	}

	var r0 resourceapi.Client
	if rf, ok := ret.Get(0).(func(string) resourceapi.Client); ok {
		r0 = rf(version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resourceapi.Client)
		}
	}

	return r0
}

// MockClient_WithVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithVersion'
type MockClient_WithVersion_Call struct {
	*mock.Call
}

// WithVersion is a helper method to define mock.On call
//   - version string
func (_e *MockClient_Expecter) WithVersion(version interface{}) *MockClient_WithVersion_Call {
	return &MockClient_WithVersion_Call{Call: _e.mock.On("WithVersion", version)}
}

func (_c *MockClient_WithVersion_Call) Run(run func(version string)) *MockClient_WithVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_WithVersion_Call) Return(_a0 resourceapi.Client) *MockClient_WithVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_WithVersion_Call) RunAndReturn(run func(string) resourceapi.Client) *MockClient_WithVersion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
